name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: homfine-laravel-dev
          POSTGRES_USER: devaja
          POSTGRES_PASSWORD: 1q2w3e4r
        options: >-
          --health-cmd="pg_isready -U devaja -d homfine-laravel-dev"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_pgsql, intl, bcmath
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Configure DB in .env
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=pgsql/' .env
          sed -i 's/DB_HOST=.*/DB_HOST=postgres/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=5432/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=homfine-laravel-dev/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=devaja/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=1q2w3e4r/' .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Clear config cache
        run: php artisan config:clear

      - name: Wait for Postgres
        run: |
          until pg_isready -h postgres -p 5432 -U devaja; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
